timeline_spec =

[
(:show, Bool, true),
(:_type, String, "slider"),
(:axisType, String, "time"),
(:currentIndex, Int, 0),
(:autoPlay, Bool, false),
(:rewind, Bool, false),
(:loop, Bool, true),
(:playInterval, Int, 2000),
(:realtime, Bool, true),
(:controlPosition, String, "left"),
(:zlevel, Int, 0),
(:z, Int, 2),
(:left, Union{String, Int}, "auto"),
(:top, Union{String, Int}, "auto"),
(:right, Union{String, Int}, "auto"),
(:bottom, Union{String, Int}, "auto"),
(:padding, Union{Int, Vector{Int}}, 5),
(:orient, String, "horizontal"),
(:inverse, Bool, false),
(:symbol, String, "emptyCircle"),
(:symbolSize, Union{Int, Vector{Int}}, 10),
(:symbolRotate, Int, nothing),
(:symbolOffset, Vector{Int}, [0, 0]),
(:lineStyle, LineStyle, nothing),
(:label, Label, nothing),
(:itemStyle, ItemStyle, nothing),
(:checkpointStyle, Dict, nothing),
(:controlStyle, Dict, nothing),
(:data, Vector{Any}, nothing),
]

primitivefactory(:Timeline, timeline_spec)
